
FROM node:20.11.1-alpine AS build

WORKDIR /dist/src/app

RUN npm cache clean --force

COPY . .
RUN npm install
RUN npm run build --prod


FROM nginx:latest AS ngi

COPY --from=build /dist/src/app/dist/zzouvenir-front/browser/ /usr/share/nginx/html
RUN ls /usr/share/nginx/html
RUN cat /usr/share/nginx/html/index.html
COPY /nginx.conf  /etc/nginx/conf.d/default.conf

EXPOSE 80
