version: "3.8"
services:

  db:
    build:
      context: .
      dockerfile: db-dockerfile
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: zzouvenir
      POSTGRES_PASSWORD: zzouvenir
    volumes:
      - data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: zzouvenir@zz.com
      PGADMIN_DEFAULT_PASSWORD: zzouvenir
    volumes:
      - pgadmin-data:/var/lib/pgadmin


  backend:
    image: xethail888/tobuy-backend:1.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"
    environment:
      - CONFIG_LOCATION=/backend/application.properties
      - DB_PASSWORD=zzouvenir
      - DB_URL=jdbc:postgresql://db:5432/zzouvenir
    depends_on:
      - db
    restart: on-failure:5

volumes:
  data:
  pgadmin-data: